fix: save current theme in localStorage
CMEPW/Smersh pull request #100
Opened 2021-04-11 18:35 UTC by sanchis

Persistent current theme.

- [ ] Set current theme persistent
- [ ] Fix styles in darkmode in mission-single view

2021-04-11 18:38 UTC, sanchis commented
Hello, I have some problems to deploy in local.
I got bad gateway (502) when I deploy the server locally.

Can you help me?
![image](https://user-images.githubusercontent.com/12100597/114316854-bb08f400-9b05-11eb-9ee7-43f9a4829189.png)

2021-04-12 21:43 UTC, jenaye commented
Hello  @sanchis ! excuse me for delay.
Can you give me the php stacktrace ? `docker-compose logs -f php`

2021-04-13 17:44 UTC, sanchis commented
> Hello @sanchis ! excuse me for delay.
> Can you give me the php stacktrace ? `docker-compose logs -f php`

**Logs php** 
```
Package doctrine/reflection is abandoned, you should avoid using it. Use roave/better-reflection instead.
Generating autoload files
composer/package-versions-deprecated: Generating version class...
composer/package-versions-deprecated: ...done generating version class
90 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
Run composer recipes at any time to see the status of your Symfony recipes.
Executing script cache:clear [OK]
Executing script assets:install public [OK]
Waiting for db to be ready...
```

**Logs db**
```
PostgreSQL Database directory appears to contain a database; Skipping initialization
2021-04-13 17:14:39.795 UTC [1] LOG: starting PostgreSQL 12.4 on x86_64-pc-linux-musl, compiled by gcc (Alpine 9.3.0) 9.3.0, 64-bit
2021-04-13 17:14:39.795 UTC [1] LOG: listening on IPv4 address "0.0.0.0", port 5432
2021-04-13 17:14:39.795 UTC [1] LOG: listening on IPv6 address "::", port 5432
2021-04-13 17:14:39.838 UTC [1] LOG: listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2021-04-13 17:14:39.942 UTC [21] LOG: database system was shut down at 2021-04-11 19:35:15 UTC
2021-04-13 17:14:40.008 UTC [1] LOG: database system is ready to accept connections
```
**Logs api**
```
2021/04/13 17:33:18 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: , request: "OPTIONS /authentication_token HTTP/1.1", upstream: "fastcgi://172.20.0.4:9000", host: "localhost:8000", referrer: "http://localhost:4200/"
172.20.0.1 - - [13/Apr/2021:17:33:18 +0000] "OPTIONS /authentication_token HTTP/1.1" 502 565 "http://localhost:4200/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36"
2021/04/13 17:33:27 [error] 6#6: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: , request: "OPTIONS /authentication_token HTTP/1.1", upstream: "fastcgi://172.20.0.4:9000", host: "localhost:8000", referrer: "http://localhost:4200/"
172.20.0.1 - - [13/Apr/2021:17:33:27 +0000] "OPTIONS /authentication_token HTTP/1.1" 502 565 "http://localhost:4200/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36"
172.20.0.1 - - [13/Apr/2021:17:33:33 +0000] "GET /api HTTP/1.1" 502 565 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36"
2021/04/13 17:33:33 [error] 6#6: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: , request: "GET /api HTTP/1.1", upstream: "fastcgi://172.20.0.4:9000", host: "localhost:8000"
172.20.0.1 - - [13/Apr/2021:17:33:33 +0000] "GET /favicon.ico HTTP/1.1" 200 32038 "http://localhost:8000/api" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36"
```

2021-04-13 21:20 UTC, Darkweak requested changes

2021-04-13 21:20 UTC, Darkweak commented on client/src/app/services/theme.service.ts
> +  private _currentTheme: Theme = localStorage.getItem('theme') || Theme.LIGHT_THEME;
Define a new Storage type that extends the AbstractStorage for the theme like the Token storage in the folder `client/src/app/storage`

2021-04-13 23:07 UTC, jenaye commented
Thx @sanchis i had the same error, its probably breaking change from last version of containers because the code didnt affect this


The hot-fix for you can be to run only the API  like this ˋdocker-compose up api` this worked for me

2021-04-13 23:18 UTC, Darkweak commented
Then could we provide a stable containers stack and upload these on the docker hub to avoid these side effects ?

2021-04-14 21:45 UTC, jenaye commented
Hello @sanchis bug fixed,  you can `git pull` then run this `docker-compose up -d --build --force-recreate --remove-orphans`

2021-04-16 08:32 UTC, sanchis commented
> Hello @sanchis bug fixed, you can `git pull` then run this `docker-compose up -d --build --force-recreate --remove-orphans`

Sorry but I keep getting the error.
```
172.20.0.1 - - [16/Apr/2021:08:21:08 +0000] "OPTIONS /authentication_token HTTP/1.1" 502 565 "http://localhost:4200/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36"
2021/04/16 08:21:08 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: , request: "OPTIONS /authentication_token HTTP/1.1", upstream: "fastcgi://172.20.0.4:9000", host: "localhost:8000", referrer: "http://localhost:4200/"
2021/04/16 08:22:54 [error] 6#6: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: , request: "GET /api HTTP/1.1", upstream: "fastcgi://172.20.0.4:9000", host: "localhost:8000"
172.20.0.1 - - [16/Apr/2021:08:22:54 +0000] "GET /api HTTP/1.1" 502 565 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36"
2021/04/16 08:22:55 [error] 6#6: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: , request: "GET /api HTTP/1.1", upstream: "fastcgi://172.20.0.4:9000", host: "localhost:8000"
172.20.0.1 - - [16/Apr/2021:08:22:55 +0000] "GET /api HTTP/1.1" 502 565 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36"
172.20.0.1 - - [16/Apr/2021:08:22:56 +0000] "GET /favicon.ico HTTP/1.1" 200 32038 "http://localhost:8000/api" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36"
```

2021-04-16 08:41 UTC, Darkweak commented
@sanchis 
Did you rebase the branch ?
`git fetch && git rebase --keep-empty origin/master`
`docker pull && docker-compose up -d --build --force-recreate --remove-orphans api`
Then run the client should do the trick

2021-04-16 09:25 UTC, sanchis commented
> @sanchis
> Did you rebase the branch ?
> `git fetch && git rebase --keep-empty origin/master`
> `docker pull && docker-compose up -d --build --force-recreate --remove-orphans api`
> Then run the client should do the trick

Yes I get the latest changes in [my fork](https://github.com/sanchis/Smersh/tree/fix/99-theme).

1. `git fetch upstream`
2. `git rebase upstream/master`
3. `git merge origin/mater` (to the current branch `fix/99-theme`)

Then I remove all container related with Smersh and remove all images.
After that I execute `docker-compose up -d --build --force-recreate --remove-orphans api`

2021-04-20 22:21 UTC, Darkweak commented
@sanchis did you wait for the `NOTICE: ready to handle connections` when you are starting the container ?
`docker-compose logs -f php` It may take some minutes to be done at the first time

2021-05-01 16:29 UTC, sanchis commented
> @sanchis did you wait for the `NOTICE: ready to handle connections` when you are starting the container ?
> `docker-compose logs -f php` It may take some minutes to be done at the first time

**Hello, excuse me for delay.**

Ops I think this is the problem. 😐
phg logs output
```
Package doctrine/reflection is abandoned, you should avoid using it. Use roave/better-reflection instead.
Generating autoload files
composer/package-versions-deprecated: Generating version class...
composer/package-versions-deprecated: ...done generating version class
117 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
Run composer recipes at any time to see the status of your Symfony recipes.
Executing script cache:clear [OK]
Executing script assets:install public [OK]
Waiting for db to be ready...
```

2021-05-01 19:31 UTC, Darkweak commented
@sanchis can you run a `make cache` then run `docker-compose down --remove-orphans && make start` ? It seems your php try to access to an unreachable db (possibly due to cache).  
If it doesn't solve your problem can you dump your `docker-compose.yml ` file here ?

2021-05-01 21:34 UTC, sanchis commented
> @sanchis can you run a `make cache` then run `docker-compose down --remove-orphans && make start` ? It seems your php try to access to an unreachable db (possibly due to cache).
> If it doesn't solve your problem can you dump your `docker-compose.yml ` file here ?

`make: *** No rule to make target 'start'.  Stop.` I think you mean `make up` ?

2021-05-01 21:38 UTC, Darkweak commented
Yes, run `make up` 👍 
Then can you provide us your discord tag to solve your problem on discord pls ?

2021-05-22 18:43 UTC, sanchis commented
![image](https://user-images.githubusercontent.com/12100597/119237640-27800580-bb3e-11eb-9571-0a97709ce8b6.png)
![image](https://user-images.githubusercontent.com/12100597/119237646-2cdd5000-bb3e-11eb-82b8-82835785023c.png)

Is good for you?
The pull request is ready for review.

Sorry for the problems and delay.

2021-05-22 19:33 UTC, Darkweak approved these changes
After this last change it looks good to me and could be merged.

2021-05-22 19:33 UTC, Darkweak commented on client/src/app/storage/Theme.ts
> +  }
```suggestion
}
```

2021-05-22 20:05 UTC, sanchis commented on client/src/app/storage/Theme.ts
> +  }
Fixed in 78e5b06

2021-05-23 13:35 UTC, jenaye approved these changes

2021-05-23 13:35 UTC, merged