[Feat] - CodiMD account attach to user
CMEPW/Smersh pull request #132
Opened 2021-08-07 17:58 UTC by jenaye

When you create new account, user gna have codimd account with same creds #33

2021-08-10 00:06 UTC, Darkweak approved these changes

2021-08-10 00:07 UTC, Darkweak requested changes

2021-08-10 00:07 UTC, Darkweak commented on api/config/services.yaml
>              - { name: doctrine.event_listener, event: prePersist, connection: default }
Remove this

2021-08-10 00:07 UTC, Darkweak commented on api/src/Listener/UserCreateListener.php
> +                'http://codimd:3000/register', [
Set this URL as constant

2021-08-10 00:07 UTC, Darkweak commented on api/src/Listener/UserCreateListener.php
> +                'POST',
Use constant for POST request

2021-08-11 08:20 UTC, Darkweak requested changes

2021-08-11 08:20 UTC, Darkweak commented on api/src/Listener/UserCreateListener.php
> +    const HTTP_CODI_METHOD = 'POST';
```suggestion
```

2021-08-11 08:20 UTC, Darkweak commented on api/src/Listener/UserCreateListener.php
> +                self::HTTP_CODI_METHOD,
```suggestion
                Request::METHOD_POST,
```

From the `HttpFoundation` namespace.

2021-08-11 08:20 UTC, Darkweak commented on api/src/Listener/UserCreateListener.php
> +                        'User-Agent' => 'Mozilla/5.0 (X11; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0',
Is it mandatory ?

2021-08-12 22:57 UTC, Darkweak requested changes

2021-08-12 22:57 UTC, Darkweak commented on api/src/Listener/UserCreateListener.php
> +
Remove empty line

2021-08-12 22:57 UTC, Darkweak commented on api/src/Listener/UserCreateListener.php
> +
Remove empty line

2021-08-20 14:31 UTC, Darkweak commented
Ready to merge @jenaye

2021-08-20 14:31 UTC, Darkweak approved these changes

2021-08-20 22:49 UTC, jenaye commented
![image](https://user-images.githubusercontent.com/15458329/130300464-0126f99a-dc3f-4619-bac8-0ba0ce3da15f.png)

2021-08-20 22:50 UTC, merged