[Feat]  - Download BurpSuite config file
CMEPW/Smersh pull request #69
Opened 2021-03-10 02:00 UTC by jenaye

2021-03-10 02:12 UTC, jenaye commented on client/src/app/services/configService.ts
> +    public getBurpConfiguration(): Observable<any> {
i probably should use other type  instead of Any

2021-03-11 17:35 UTC, Darkweak requested changes

2021-03-11 17:35 UTC, Darkweak commented on client/src/app/components/mission-single/mission-single.component.ts
> +      const file = new Blob([JSON.stringify(e)], {
```suggestion
      const file = new Blob([JSON.stringify({
        ...e,
        target: {
          ...e.target,
          scope: {
            include: [....e.target.scope, ...hosts.map(h => ({enabled: true, prefix: host.name}))]
          }
        }
      })], {
```

2021-03-11 17:39 UTC, Darkweak requested changes

2021-03-11 17:39 UTC, Darkweak commented on client/src/app/components/mission-single/mission-single.component.ts
> +      const a = document.createElement('a');
make a generic function like `exportDocument(name: string, data: unknown)`

2021-03-12 18:02 UTC, Darkweak approved these changes

2021-03-12 18:05 UTC, Darkweak requested changes

2021-03-12 18:05 UTC, Darkweak commented on client/src/app/services/configService.ts
> +
```suggestion
import burpConfiguration from 'public/assets/burp.json';
```

2021-03-12 18:05 UTC, Darkweak commented on client/src/app/services/configService.ts
> +    return this.http.get('/assets/burp.json');
```suggestion
    return burpConfiguration;
```

2021-03-12 18:58 UTC, Darkweak approved these changes

2021-03-12 18:59 UTC, merged